name: CI

on:
  push:
    branches: [midnight]
    paths-ignore:
      - "ActionPriorityLists/**"
      - "SpellDataDump/**"
      - "dbc_extract3/**"
      - "casc_extract/**"
      - "doc/**"
      - "**.md"
  pull_request:
    branches: [midnight]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  spec-test:
    needs: build
    uses: ./.github/workflows/spec_test.yml
    with:
      cache-key: ubuntu-gcc-14-release-${{ github.sha }}

  ubuntu-test:
    needs: build
    uses: ./.github/workflows/ubuntu_test.yml
    with:
      cache-key: ubuntu-gcc-14-release-${{ github.sha }}
