name: ubuntu-test

on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: true

env:
  SIMC_PROFILE: profiles/CI.simc

jobs:
  ubuntu-smoke-test:
    name: ubuntu-smoke-test
    runs-on: ubuntu-24.04
    env:
      UBSAN_OPTIONS: print_stacktrace=1
      SIMC_ARGS: output=/dev/null html=/dev/null json=/dev/null cleanup_threads=1

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            profiles
            tests
            generate_profiles_ci.sh
            .git
          key: ${{ inputs.cache-key }}

      - name: Spell query sanity check
        run: |
          ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS spell_query=spell > /dev/null

      - name: CI profile — Patchwerk
        run: |
          ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS \
            $SIMC_PROFILE iterations=10

      - name: CI profile — DungeonSlice
        run: |
          ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS \
            $SIMC_PROFILE iterations=10 fight_style=DungeonSlice \
            allow_experimental_specializations=1
